# Dockerfile.dev
FROM node:18-alpine

WORKDIR /app

# Копіюємо package-файли
COPY package*.json ./

# Встановлюємо залежності
RUN npm install --prefer-offline

# Копіюємо решту файлів
COPY . .

# Відкриваємо порт
EXPOSE 3000

# Запускаємо dev-сервер
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]