# frontend/Dockerfile.dev
# Stage 1: Build the React application
FROM node:18-alpine as build-stage

WORKDIR /app

# Копіюємо package.json та package-lock.json
COPY package*.json ./

# Встановлюємо залежності
RUN npm ci --only=production --prefer-offline

# Копіюємо решту файлів проекту
COPY . .

# Будуємо проект
RUN npm run build

# Stage 2: Serve the application with Nginx
FROM nginx:stable-alpine as production-stage

# Копіюємо ПОБУДОВАНІ файли з build-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Копіюємо конфігураційний файл nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Відкриваємо порт, на якому NGINX слухає (відповідно до nginx.conf)
EXPOSE 80

# Запуск додатку
CMD ["nginx", "-g", "daemon off;"]