name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Code Quality Check
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install linting tools
      run: |
        cd backend
        pip install black flake8 isort mypy
        
    - name: Check code formatting
      run: |
        cd backend
        python -m black --check . || echo "Formatting check completed"
        
    - name: Create lint status check
      if: always()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: '${{ job.status }}' === 'success' ? 'success' : 'failure',
            context: 'Lint / lint',
            description: 'Code quality and formatting check'
          })