name: Security Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Bandit security linter
        run: |
          cd backend
          pip install bandit
          python -m bandit -r . -f html -o security-report.html || true
          
      - name: Run Safety check
        run: |
          cd backend
          pip install safety
          python -m safety check --json || true